//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NalburUrunleri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageTable
    {
        public int Id { get; set; }
        public string IMAGEURL { get; set; }
        public int ProductID { get; set; }
    
        public virtual ProductTable ProductTable { get; set; }
    }
}
